### ISSUE TITLE
Unable to configure two vehicles

### ISSUE THREAD

**Issue by maxbethge** [donker/MMM-TeslamateLocation#1]
It doesn't seem possible to accurately configure 2 instances of the module to display 2 different vehicle locations. The two maps get grouped together at the first instance's screen position regardless of the position of the second instance. The second header is lost too. The example shows two instances that are supposed to be in top_center and top_right.
![2023-12-22 21_06_39-Greenshot](https://github.com/donker/MMM-TeslamateLocation/assets/18727371/f7798835-1ff5-4075-b0de-60ffcecb6a19)

**Comment by donker** [comment]
I had so much trouble to get the map to show up correctly for a single car, I'm not sure two cars will ever work. Maybe when I get a second Tesla it'll become a thing to invest the time in.

**Comment by maxbethge** [comment]
I actually got it to work by creating a local copy of the module, renaming it in various files, and then changing the callback functions (e.g. window.setLatitude2). I didn't see any easy way to dynamically create these functions based on the car Id and I highly doubt all the functionality works correctly in both instances but for now it 'works'.

Thanks for your work in creating the module :)

**Comment by donker** [comment]
Awesome. Thanks.
